In [2]:
class Variable:
    def __init__(self, data):
        self.data = data

        
        
import numpy as np
data = np.array(1.0)
x = Variable(data)
print(x.data)

1.0


In [3]:
x.data = np.array(2.0)
print(x.data)

2.0


In [5]:
x = np.array(1)
x.ndim

0

In [6]:
x = np.array([1,2,3])
x.ndim

1

In [7]:
x = np.array([[1,2,3],[4,5,6]])
x.ndim

2

In [1]:
import numpy as np

In [7]:
seq_data = [np.random.randn(1,1) for _ in range(10)]
seq_data

[array([[ 0.84137679],
        [-0.15745535]]),
 array([[-2.12186862e-01],
        [-3.73083946e-05]]),
 array([[1.25991464],
        [0.4820641 ]]),
 array([[-0.16238486],
        [-1.73805067]]),
 array([[0.29912791],
        [0.76639134]]),
 array([[-0.15670421],
        [ 0.53782398]]),
 array([[ 0.31149206],
        [-0.17092735]]),
 array([[-0.98965092],
        [-1.07751139]]),
 array([[0.48919775],
        [1.58073222]]),
 array([[ 0.39827177],
        [-1.47650672]])]

In [3]:
seq_data

[array([[0.11663025]]),
 array([[0.14450198]]),
 array([[0.37360298]]),
 array([[1.45492687]]),
 array([[0.92427943]]),
 array([[0.11367701]]),
 array([[0.06833609]]),
 array([[0.84972725]]),
 array([[0.98659654]]),
 array([[0.64967799]]),
 array([[0.36032512]]),
 array([[0.6773842]]),
 array([[-2.21426834]]),
 array([[0.64591219]]),
 array([[-1.61865507]]),
 array([[0.40154079]]),
 array([[0.95918523]]),
 array([[0.01881067]]),
 array([[0.16632894]]),
 array([[-1.9298304]]),
 array([[-0.36205214]]),
 array([[-0.38853214]]),
 array([[-0.812516]]),
 array([[-0.27127978]]),
 array([[1.31704253]]),
 array([[0.96212805]]),
 array([[-0.51253355]]),
 array([[-0.5911901]]),
 array([[1.22086777]]),
 array([[-0.95536584]]),
 array([[-0.74384039]]),
 array([[0.28395547]]),
 array([[0.87958218]]),
 array([[-1.73176712]]),
 array([[1.02286762]]),
 array([[0.33514303]]),
 array([[-1.31001287]]),
 array([[0.45743667]]),
 array([[-0.96010053]]),
 array([[-0.1911944]]),
 array([[-1.02189709]]),
 array